{{- if and .Values.deploymentType (ne .Values.deploymentType "Deployment") }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "default.svc-headless-name" . }}
  labels:
    {{- include "default.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "default.selectorLabels" . | nindent 4 }}
{{- end }}
